# Generated by Django 6.0.7 on 2026-07-11 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('companies', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected'), ('OFFERED', 'Offered'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('OFFER_REJECTED', 'Offer Rejected')], default='APPLIED', max_length=25)),
                ('cover_letter', models.TextField(blank=True)),
                ('match_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('suggested_skills', models.JSONField(blank=True, default=list)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes by company/officer')),
                ('resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='students.resume')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('INTERNSHIP', 'Internship'), ('CONTRACT', 'Contract')], default='FULL_TIME', max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('salary_package', models.CharField(help_text='e.g. 6-8 LPA', max_length=100)),
                ('min_cgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('max_backlogs', models.PositiveIntegerField(default=0)),
                ('experience_required', models.CharField(default='Fresher', max_length=100)),
                ('vacancies', models.PositiveIntegerField(default=1)),
                ('last_date_to_apply', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('FILLED', 'Filled')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.companyprofile')),
                ('eligible_departments', models.ManyToManyField(blank=True, related_name='eligible_jobs', to='accounts.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
